## setup compilation flags
include(CheckCXXCompilerFlag)

# discover compiler C++ standard support
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
    check_cxx_compiler_flag("-std:c++14" COMPILER_SUPPORTS_CXX14)
    check_cxx_compiler_flag("-std:c++17" COMPILER_SUPPORTS_CXX17)
    check_cxx_compiler_flag("-std:c++20" COMPILER_SUPPORTS_CXX20)
    check_cxx_compiler_flag("-std:c++23" COMPILER_SUPPORTS_CXX23)
    if(COMPILER_SUPPORTS_CXX14)
        set(CMAKE_CXX14_STANDARD_COMPILE_OPTION "-std:c++14")
        set(CMAKE_CXX14_EXTENSION_COMPILE_OPTION "-std:c++14")
    endif()
    if(COMPILER_SUPPORTS_CXX17)
        set(CMAKE_CXX17_STANDARD_COMPILE_OPTION "-std:c++17")
        set(CMAKE_CXX17_EXTENSION_COMPILE_OPTION "-std:c++17")
    endif()
    if(COMPILER_SUPPORTS_CXX20)
        set(CMAKE_CXX20_STANDARD_COMPILE_OPTION "-std:c++20")
        set(CMAKE_CXX20_EXTENSION_COMPILE_OPTION "-std:c++20")
    endif()
    if(COMPILER_SUPPORTS_CXX23)
        set(CMAKE_CXX23_STANDARD_COMPILE_OPTION "-std:c++23")
        set(CMAKE_CXX23_EXTENSION_COMPILE_OPTION "-std:c++23")
    endif()
elseif("${CMAKE_CXX_COMPILER_ID}" MATCHES "^(AppleClang|Clang|GNU)$")
    check_cxx_compiler_flag("-std=c++14" COMPILER_SUPPORTS_CXX14)
    check_cxx_compiler_flag("-std=c++17" COMPILER_SUPPORTS_CXX17)
    check_cxx_compiler_flag("-std=c++20" COMPILER_SUPPORTS_CXX20)
    check_cxx_compiler_flag("-std=c++23" COMPILER_SUPPORTS_CXX23)
    if(COMPILER_SUPPORTS_CXX14)
        set(CMAKE_CXX14_STANDARD_COMPILE_OPTION "-std=c++14")
        set(CMAKE_CXX14_EXTENSION_COMPILE_OPTION "-std=gnu++14")
    endif()
    if(COMPILER_SUPPORTS_CXX17)
        set(CMAKE_CXX17_STANDARD_COMPILE_OPTION "-std=c++17")
        set(CMAKE_CXX17_EXTENSION_COMPILE_OPTION "-std=gnu++17")
    endif()
    if(COMPILER_SUPPORTS_CXX20)
        set(CMAKE_CXX20_STANDARD_COMPILE_OPTION "-std=c++20")
        set(CMAKE_CXX20_EXTENSION_COMPILE_OPTION "-std=gnu++20")
    endif()
    if(COMPILER_SUPPORTS_CXX23)
        set(CMAKE_CXX23_STANDARD_COMPILE_OPTION "-std=c++23")
        set(CMAKE_CXX23_EXTENSION_COMPILE_OPTION "-std=gnu++23")
    endif()
endif()
